language: python
python:
- '2.7'
- '3.3'
- '3.4'
install: make deps
script: make test
deploy:
  provider: pypi
  user: GochoMugoI
  password:
    secure: VqAPAqM4cpblt60p4nEDKylz8JBPYS9OqJCiP8+OWR80ETbz4i34ttaJHPTIq6qwiIQl9M0Gp6qC/VYrOBOGilWtXMMW4vhukwadMfCTEOmwdqFpyUtT7I+i1Fcjsyzo7vM9TRsN+ZB27IQQw+wlHceXcjo6AIrQqhDiUgaC35w=
  on:
    tags: true
    repo: GochoMugo/remindme
