language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
install: make deps
script: make test
deploy:
  provider: pypi
  user: GochoMugoI
  password:
    secure: N32Gv45FeX9qpoqj5Ui/bnNhas407j/PVYv/r6drCsGz1TpTDEZHVldbzeNye9YNHqnD7XJ0MOn+4EL75JDK7OhUG5rV4f/HE5g9wcAORF9llCBb1WH7hG12fSgRKDaLoH/cJIPNwo+XAMInaw7Ll/axK+U7mIS6tNoqWi/iAE4=
  on:
    tags: true
    repo: GochoMugo/remindme
